### ISSUE TITLE
the shell

### ISSUE THREAD

**Issue by mkuzak** [xenon-middleware/Xenon-examples#73]
on line 277 of xenon-tutorial.tex it states:
"The shell should be Bash"
what happens if someone has `zsh` or `csh`? 
Users may think, they need to switch shells to be able to use xenon

**Comment by jspaaks** [comment]
Some maybe change it to something that indicates that I'll be using Bash in this tutorial? I don't want to cover all the other shells out there.

**Comment by mkuzak** [comment]
I don't think we have to cover all the shells, it will 99% work on other shells, so just say use shell instead of Bash
