### ISSUE TITLE
`gradlew dependencies` not only prints dependecies

### ISSUE THREAD

**Issue by mkuzak** [xenon-middleware/Xenon-examples#76]
On [line 381](https://github.com/NLeSC/Xenon-examples/blob/324ecc8b657ab0c6e0b7610027023fd705ad0076/doc/tutorial/xenon-tutorial.tex#L383) of xenon-tutorial.tex it states:

> `./gradlew depencencies` prints a list of dependencies

but the output states:

> `BUILD SUCCESFULL`

which suggests it did something more.

**Comment by jspaaks** [comment]
Agreed, but I don't think anything is built -- it's just the default message.
